In [15]:
import pandas as pd

df = pd.read_parquet("./data/003_feature_engineered/1min_power_load.parquet")
df.head()

,timestamp,load,workday,lag_1,lag_2,lag_3,lag_4,lag_5,lag_10,lag_15,...,slope_30,slope_60,second,minute,hour,time_of_day,day,weekday,is_weekend,month
0,2025-11-28 00:00:00,1912.400000,full,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,0,0,Night,28,4,0,11
1,2025-11-28 00:01:00,1908.233333,full,1912.400000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,1,0,Night,28,4,0,11
2,2025-11-28 00:02:00,1643.183333,full,1908.233333,1912.400000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,2,0,Night,28,4,0,11
3,2025-11-28 00:03:00,2992.950000,full,1643.183333,1908.233333,1912.400000,NaN,NaN,NaN,NaN,...,NaN,NaN,0,3,0,Night,28,4,0,11
4,2025-11-28 00:04:00,1106.000000,full,2992.950000,1643.183333,1908.233333,1912.4,NaN,NaN,NaN,...,NaN,NaN,0,4,0,Night,28,4,0,11

,timestamp,load,workday,lag_1,lag_2,lag_3,lag_4,lag_5,lag_10,lag_15,...,slope_30,slope_60,second,minute,hour,time_of_day,day,weekday,is_weekend,month
0,2025-11-28 00:00:00,1912.400000,full,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,0,0,Night,28,4,0,11
1,2025-11-28 00:01:00,1908.233333,full,1912.400000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,1,0,Night,28,4,0,11
2,2025-11-28 00:02:00,1643.183333,full,1908.233333,1912.400000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,2,0,Night,28,4,0,11
3,2025-11-28 00:03:00,2992.950000,full,1643.183333,1908.233333,1912.400000,NaN,NaN,NaN,NaN,...,NaN,NaN,0,3,0,Night,28,4,0,11
4,2025-11-28 00:04:00,1106.000000,full,2992.950000,1643.183333,1908.233333,1912.4,NaN,NaN,NaN,...,NaN,NaN,0,4,0,Night,28,4,0,11